#ifndef KNN_MFCC_CONFIG_H_INCLUDED
#define KNN_MFCC_CONFIG_H_INCLUDED
#define NUM_CLASSES 9
#define NUM_NEIGHBORS 3
#define NUM_FEATURES 13
#define NUM_SAMPLES 500
extern char* LABELS[NUM_CLASSES];
extern const float DATA[NUM_SAMPLES][NUM_FEATURES];
extern const int DATA_LABELS[NUM_SAMPLES];
#endif
#define NUM_UNIQUE_CLASSES 9
extern const char* CLASS_NAMES[NUM_UNIQUE_CLASSES];
